# Generated by Django 4.1.7 on 2023-04-22 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('mid_name', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=8)),
                ('is_admin', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('wait', 'Ожидающая ответа'), ('closed', 'Решена')], default='Новая', max_length=20)),
                ('category', models.CharField(choices=[('oscod', 'Пользователи AD, Медпочты'), ('secure', 'VipNet, защищенная сеть'), ('is', 'Информационные системы')], max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attach', models.FileField(upload_to='files/attach_tickets/%Y-%m-%d/')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_ticket.Ticket.agent+', to='create_ticket.user')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_ticket.Ticket.author+', to='create_ticket.user')),
            ],
        ),
    ]
